// author: Onne Gorter, license: MIT (see license.txt)
// simple text type, wraps a char array with size and tag

#include "trace-off.h"

static tlKind _tlTextKind;
tlKind* tlTextKind = &_tlTextKind;

static tlText* _tl_emptyText;

// TODO short strings should be "inline" saves finalizer
struct tlText {
    tlHead head;
    const char* data;
    int len;
};

tlText* tlTextEmpty() { return _tl_emptyText; }

tlText* tlTextFromStatic(const char* s, int len) {
    trace("%s", s);
    tlText* text = tlAlloc(tlTextKind, sizeof(tlText));
    text->data = s;
    text->len = (len > 0)?len:strlen(s);
    return text;
}

tlText* tlTextFromTake(char* s, int len) {
    trace("%s", s);
    tlText* text = tlAlloc(tlTextKind, sizeof(tlText));
    text->data = s;
    text->len = (len > 0)?len:strlen(s);
    return text;
}

tlText* tlTextFromCopy(const char* s, int len) {
    trace("%s", s);
    if (len <= 0) len = strlen(s);
    //assert(len < TL_MAX_INT);
    char *data = malloc_atomic(len + 1);
    if (!data) return null;
    memcpy(data, s, len + 1);
    return tlTextFromTake(data, len);
}

const char* tlTextData(tlText *text) {
    assert(tlTextIs(text));
    return text->data;
}

int tlTextSize(tlText* text) {
    assert(tlTextIs(text));
    return text->len;
}

tlValue tlTextEquals(tlText* left, tlText* right) {
    if (tlTextSize(left) != tlTextSize(right)) return tlFalse;
    return tlBOOL(strcmp(tlTextData(left), tlTextData(right)) == 0);
}

tlText* tlTextSub(tlText* from, int first, int size) {
    if (tlTextSize(from) == size) return from;
    char* data = malloc_atomic(size + 1);
    if (!data) return null;
    memcpy(data, from->data + first, size);
    data[size] = 0;

    return tlTextFromTake(data, size);
}

tlText* tlTextCat(tlText* left, tlText* right) {
    int size = tlTextSize(left) + tlTextSize(right);
    char* data = malloc_atomic(size + 1);
    if (!data) return null;
    memcpy(data, left->data, tlTextSize(left));
    memcpy(data + tlTextSize(left), right->data, tlTextSize(right));
    data[size] = 0;
    return tlTextFromTake(data, size);
}

// generated by parser for "foo: $foo" etc...
// TODO args.map(_.toText) do it more correctly invoking toText methods
INTERNAL tlValue _Text_cat(tlArgs* args) {
    int argc = tlArgsSize(args);
    trace("%d", argc);
    tlList* list = null;
    int size = 0;
    for (int i = 0; i < argc; i++) {
        tlValue v = tlArgsGet(args, i);
        trace("%d: %s", i, tl_str(v));
        if (tlTextIs(v)) {
            size += tlTextAs(v)->len;
        } else {
            if (!list) list = tlListNew(argc);
            tlText* text = tlTextFromCopy(tl_str(tlArgsGet(args, i)), 0);
            size += text->len;
            tlListSet_(list, i, text);
        }
    }

    char* data = malloc_atomic(size + 1);
    if (!data) return null;
    size = 0;
    for (int i = 0; i < argc; i++) {
        const char* str;
        int len;
        tlValue v = tlArgsGet(args, i);
        if (tlTextIs(v)) {
            str = tlTextAs(v)->data;
            len = tlTextAs(v)->len;
        } else {
            tlText* text = tlTextAs(tlListGet(list, i));
            str = text->data;
            len = text->len;
        }
        memcpy(data + size, str, len);
        size += len;
    }
    data[size] = 0;
    return tlTextFromTake(data, size);
}

INTERNAL tlValue _text_toText(tlArgs* args) {
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    return text;
}
INTERNAL tlValue _text_toSym(tlArgs* args) {
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    return tlSymFromText(text);
}
INTERNAL tlValue _text_size(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    return tlINT(tlTextSize(text));
}

INTERNAL tlValue _text_search(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    tlText* find = tlTextCast(tlArgsGet(args, 0));
    if (!find) TL_THROW("expected a Text");
    const char* p = strstr(tlTextData(text), tlTextData(find));
    if (!p) return tlNull;
    return tlINT(p - tlTextData(text));
}

INTERNAL tlValue _text_cat(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    tlText* add = tlTextCast(tlArgsGet(args, 0));
    if (!add) TL_THROW("arg must be a Text");

    return tlTextCat(text, add);
}

INTERNAL tlValue _text_char(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");

    int at = tl_int_or(tlArgsGet(args, 0), 0);
    int size = tlTextSize(text);
    if (at < 0) at = size + at;
    if (!(at >=0 && at < size)) return tlNull;
    return tlINT(text->data[at]);
}

INTERNAL tlValue _text_slice(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    int size = tlTextSize(text);
    int first = tl_int_or(tlArgsGet(args, 0), 0);
    int last = tl_int_or(tlArgsGet(args, 1), size);

    trace("%d %d (%s)%d", first, last, text->data, size);

    if (first < 0) first = size + first;
    if (first < 0) return tlTextEmpty();
    if (first >= size) return tlTextEmpty();
    if (last <= 0) last = size + last;
    if (last < first) return tlTextEmpty();
    if (last >= size) last = size;

    trace("%d %d (%s)%d", first, last, text->data, size);

    return tlTextSub(text, first, last - first);
}

static inline char escape(char c) {
    switch (c) {
        case '\0': return '0';
        case '\t': return 't';
        case '\n': return 'n';
        case '\r': return 'r';
        case '"': return '"';
        case '$': return '$';
        case '\\': return '\\';
        default:
            assert(c >= 32);
            return 0;
    }
}

INTERNAL tlValue _text_escape(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    const char* data = tlTextData(text);
    int size = tlTextSize(text);
    int slashes = 0;
    for (int i = 0; i < size; i++) if (escape(data[i])) slashes++;
    if (slashes == 0) return text;

    char* ndata = malloc(size + slashes + 1);
    int j = 0;
    for (int i = 0; i < size; i++, j++) {
        char c;
        if ((c = escape(data[i]))) {
            ndata[j++] = '\\';
            ndata[j] = c;
        } else {
            ndata[j] = data[i];
        }
    }
    assert(size + slashes == j);
    return tlTextFromTake(ndata, j);
}

INTERNAL tlValue _text_strip(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");

    if (tlTextSize(text) == 0) return text;
    const char* data = tlTextData(text);
    int len = tlTextSize(text);
    int left = 0;
    int right = len; // assuming zero byte at end

    while (left < right && data[left] <= 32) left++;
    while (right > left && data[right] <= 32) right--;
    right++; // always a zero byte

    trace("%d %d", left, right);
    if (left == len) return _tl_emptyText;
    if (left == 0 && right == len) return text;

    int size = right - left;
    assert(size > 0 && size < tlTextSize(text));
    char* ndata = malloc(size + 1);
    memcpy(ndata, data + left, size);
    ndata[size] = 0;
    return tlTextFromTake(ndata, size);
}

static int intmin(int left, int right) { return (left<right)?left:right; }

INTERNAL tlValue _text_startsWith(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    tlText* start = tlTextCast(tlArgsGet(args, 0));
    if (!start) TL_THROW("arg must be a Text");
    int from = tl_int_or((tlArgsGet(args, 1)), 0);


    int textsize = tlTextSize(text);
    int startsize = tlTextSize(start);
    if (textsize + from < startsize) return tlFalse;

    int r = strncmp(tlTextData(text) + from, tlTextData(start), startsize);
    return tlBOOL(r == 0);
}

INTERNAL tlValue _text_endsWith(tlArgs* args) {
    trace("");
    tlText* text = tlTextCast(tlArgsTarget(args));
    if (!text) TL_THROW("this must be a Text");
    tlText* start = tlTextCast(tlArgsGet(args, 0));
    if (!start) TL_THROW("arg must be a Text");

    int textsize = tlTextSize(text);
    int startsize = tlTextSize(start);
    if (textsize < startsize) return tlFalse;

    int r = strncmp(tlTextData(text) + textsize - startsize, tlTextData(start), startsize);
    return tlBOOL(r == 0);
}

INTERNAL const char* textToText(tlValue v, char* buf, int size) {
    return tlTextData(tlTextAs(v));
}
static tlKind _tlTextKind = {
    .name = "text",
    .toText = textToText,
};

static tlSym s_class;
static void text_init() {
    _tl_emptyText = tlTEXT("");
    _tlTextKind.klass = tlClassMapFrom(
        "toText", _text_toText,
        "toSym", _text_toSym,
        "size", _text_size,
        "startsWith", _text_startsWith,
        "endsWith", _text_endsWith,
        "search", _text_search,
        "char", _text_char,
        "get", _text_char,
        "slice", _text_slice,
        "cat", _text_cat,
        "escape", _text_escape,
        "strip", _text_strip,
        "each", null,
        "split", null,
        "replace", null,
        "eval", null,
        null
    );
    tlMap* constructor = tlClassMapFrom(
        "call", _Text_cat,
        "class", null,
        null
    );
    tlMapSetSym_(constructor, s_class, _tlTextKind.klass);
    tl_register_global("Text", constructor);
}

