// autogenerated:
//   $ cd hotelparser
//   $ make boot
// ** do not edit ** do not edit ** do not edit ** do not edit **
#include "tlmeta.c"

static const char* const colors[] = {"","pad",null};
static State r_name_2_1_1(Parser*, int);
static State r_name_2_1_2(Parser*, int);
static State r_name_2_1_3(Parser*, int);
static State r_name_2_1(Parser*, int);
static State r_name(Parser*, int);
static State r_cstyle_2_1_1(Parser*, int);
static State r_cstyle_2_1(Parser*, int);
static State r_cstyle(Parser*, int);
static State r_sp(Parser*, int);
static State r_cdata_2_1(Parser*, int);
static State r_cdata_2(Parser*, int);
static State r_cdata(Parser*, int);
static State r_open_2_1(Parser*, int);
static State r_open_2_2(Parser*, int);
static State r_open_2(Parser*, int);
static State r_open(Parser*, int);
static State r_start(Parser*, int);
static State r_attr_1(Parser*, int);
static State r_attr_2(Parser*, int);
static State r_attr_3(Parser*, int);
static State r_attr_4_1_1(Parser*, int);
static State r_attr_4_1_2(Parser*, int);
static State r_attr_4_1(Parser*, int);
static State r_attr(Parser*, int);
static State r_unknown_2_1_1(Parser*, int);
static State r_unknown_2_1_2(Parser*, int);
static State r_unknown_2_1(Parser*, int);
static State r_unknown(Parser*, int);
static State r_escape_1(Parser*, int);
static State r_escape_2(Parser*, int);
static State r_escape_3(Parser*, int);
static State r_escape_4(Parser*, int);
static State r_escape_5(Parser*, int);
static State r_escape_6_1(Parser*, int);
static State r_escape_6_2(Parser*, int);
static State r_escape_6(Parser*, int);
static State r_escape(Parser*, int);
static State r_aname_2_1_1(Parser*, int);
static State r_aname_2_1_2(Parser*, int);
static State r_aname_2_1_3(Parser*, int);
static State r_aname_2_1_4(Parser*, int);
static State r_aname_2_1(Parser*, int);
static State r_aname(Parser*, int);
static State r_end_2(Parser*, int);
static State r_end(Parser*, int);
static State r_ws_2(Parser*, int);
static State r_ws(Parser*, int);
static State r_script_2(Parser*, int);
static State r_script(Parser*, int);
static State r_attrs_2_1(Parser*, int);
static State r_attrs_3_1(Parser*, int);
static State r_attrs(Parser*, int);
static State r_text_2_1_1(Parser*, int);
static State r_text_2_1(Parser*, int);
static State r_text(Parser*, int);
static State r_comment_2_1_1(Parser*, int);
static State r_comment_2_1(Parser*, int);
static State r_comment(Parser*, int);
static State r_seq_2_1(Parser*, int);
static State r_seq_2_2(Parser*, int);
static State r_seq_2_3(Parser*, int);
static State r_seq_2_4(Parser*, int);
static State r_seq_2_5(Parser*, int);
static State r_seq_2_6(Parser*, int);
static State r_seq_2_7(Parser*, int);
static State r_seq_2(Parser*, int);
static State r_seq(Parser*, int);
static State r_style_2(Parser*, int);
static State r_style(Parser*, int);
static State r_wsnl(Parser*, int);
static State r_cscript_2_1_1(Parser*, int);
static State r_cscript_2_1(Parser*, int);
static State r_cscript(Parser*, int);
static State r_close_2(Parser*, int);
static State r_close(Parser*, int);
static State r_string_1_1_1_1(Parser*, int);
static State r_string_1_1_1(Parser*, int);
static State r_string_1(Parser*, int);
static State r_string_2_1_1_1(Parser*, int);
static State r_string_2_1_1(Parser*, int);
static State r_string_2(Parser*, int);
static State r_string(Parser*, int);

static State r_name_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_name_2_1_1", _start);
 int _pos = _start;
 State _r = r_sp(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_name_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_name_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_name_2_1_1", _start);
}
static State r_name_2_1_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_name_2_1_2", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_name_2_1_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_name_2_1_2");*/ return _r; }
 return parser_fail(_p, "r_name_2_1_2", _start);
}
static State r_name_2_1_3(Parser* _p, int _start) { // and
 parser_enter(_p, "r_name_2_1_3", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "/>");
 if (_r.ok) return parser_pass(_p, "r_name_2_1_3", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_name_2_1_3");*/ return _r; }
 return parser_fail(_p, "r_name_2_1_3", _start);
}
static State r_name_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_name_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_name_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_name_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_name_2_1_2);
 if (!_r.ok) { return parser_fail(_p, "r_name_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_name_2_1_3);
 if (!_r.ok) { return parser_fail(_p, "r_name_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_name_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_name_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_name(Parser* _p, int _start) { // and
 parser_enter(_p, "r_name", _start);
 int _pos = _start;
 State _r;
 _r = meta_star(_p, _pos, r_name_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_name", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_name", 0, _start, state_ok(_pos, _v));
}
static State r_cstyle_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cstyle_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "</style");
 if (_r.ok) return parser_pass(_p, "r_cstyle_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_cstyle_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_cstyle_2_1_1", _start);
}
static State r_cstyle_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cstyle_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_cstyle_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_cstyle_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_cstyle_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_cstyle_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_cstyle(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cstyle", _start);
 int _pos = _start;
 State _r;
 _r = meta_star(_p, _pos, r_cstyle_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_cstyle", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_cstyle", 0, _start, state_ok(_pos, _v));
}
static State r_sp(Parser* _p, int _start) { // or
 parser_enter(_p, "r_sp", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, " ");
 if (_r.ok) return parser_pass(_p, "r_sp", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_sp");*/ return _r; }
 _r = prim_text(_p, _pos, "\t");
 if (_r.ok) return parser_pass(_p, "r_sp", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_sp");*/ return _r; }
 _r = prim_text(_p, _pos, "\r");
 if (_r.ok) return parser_pass(_p, "r_sp", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_sp");*/ return _r; }
 _r = prim_text(_p, _pos, "\n");
 if (_r.ok) return parser_pass(_p, "r_sp", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_sp");*/ return _r; }
 return parser_fail(_p, "r_sp", _start);
}
static State r_cdata_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cdata_2_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "]]>");
 if (_r.ok) return parser_pass(_p, "r_cdata_2_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_cdata_2_1");*/ return _r; }
 return parser_fail(_p, "r_cdata_2_1", _start);
}
static State r_cdata_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cdata_2", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_cdata_2_1);
 if (!_r.ok) { return parser_fail(_p, "r_cdata_2", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_cdata_2", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_cdata_2", 0, _start, state_ok(_pos, _v));
}
static State r_cdata(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cdata", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<![CDATA[");
 if (!_r.ok) { return parser_fail(_p, "r_cdata", _pos); }
 _pos = _r.pos;
 _r = r_cdata_2(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_cdata", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 _r = prim_text(_p, _pos, "]]>");
 if (!_r.ok) { return parser_fail(_p, "r_cdata", _pos); }
 _pos = _r.pos;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_cdata", 0, _start, state_ok(_pos, _v));
}
static State r_open_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_open_2_1", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_open_2_1", _pos); }
 _pos = _r.pos;
 _r = state_ok(_pos, tlSTR("open"));
 if (!_r.ok) { return parser_fail(_p, "r_open_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_open_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_open_2_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_open_2_2", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "/");
 if (!_r.ok) { return parser_fail(_p, "r_open_2_2", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open_2_2", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_open_2_2", _pos); }
 _pos = _r.pos;
 _r = state_ok(_pos, tlSTR("selfclose"));
 if (!_r.ok) { return parser_fail(_p, "r_open_2_2", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_open_2_2", 0, _start, state_ok(_pos, _v));
}
static State r_open_2(Parser* _p, int _start) { // or
 parser_enter(_p, "r_open_2", _start);
 int _pos = _start;
 State _r;
 _r = r_open_2_1(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_open_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_open_2");*/ return _r; }
 _r = r_open_2_2(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_open_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_open_2");*/ return _r; }
 return parser_fail(_p, "r_open_2", _start);
}
static State r_open(Parser* _p, int _start) { // and
 parser_enter(_p, "r_open", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<");
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 _r = r_name(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 tlHandle name = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 _r = r_attrs(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 tlHandle attrs = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 _r = r_open_2(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_open", _pos); }
 _pos = _r.pos;
 tlHandle type = _r.value;
 tlHandle _v = tlObjectFrom("name", name, "attrs", attrs, "type", type, null);
 return parser_pass(_p, "r_open", 0, _start, state_ok(_pos, _v));
}
static State r_start(Parser* _p, int _start) { // and
 parser_enter(_p, "r_start", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_start", _pos); }
 _pos = _r.pos;
 _r = r_seq(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_start", _pos); }
 _pos = _r.pos;
 tlHandle ls = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_start", _pos); }
 _pos = _r.pos;
 _r = r_end(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_start", _pos); }
 _pos = _r.pos;
 tlHandle _v = ls;
 return parser_pass(_p, "r_start", 0, _start, state_ok(_pos, _v));
}
static State r_attr_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_1", _start);
 int _pos = _start;
 State _r;
 _r = r_aname(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_1", _pos); }
 _pos = _r.pos;
 tlHandle k = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_1", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "=");
 if (!_r.ok) { return parser_fail(_p, "r_attr_1", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_1", _pos); }
 _pos = _r.pos;
 _r = r_string(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_1", _pos); }
 _pos = _r.pos;
 tlHandle v = _r.value;
 tlHandle _v = tlObjectFrom("k", k, "v", v, null);
 return parser_pass(_p, "r_attr_1", 0, _start, state_ok(_pos, _v));
}
static State r_attr_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_2", _start);
 int _pos = _start;
 State _r;
 _r = r_aname(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_2", _pos); }
 _pos = _r.pos;
 tlHandle k = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_2", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "=");
 if (!_r.ok) { return parser_fail(_p, "r_attr_2", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_2", _pos); }
 _pos = _r.pos;
 _r = r_name(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_2", _pos); }
 _pos = _r.pos;
 tlHandle v = _r.value;
 tlHandle _v = tlObjectFrom("k", k, "v", v, null);
 return parser_pass(_p, "r_attr_2", 0, _start, state_ok(_pos, _v));
}
static State r_attr_3(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_3", _start);
 int _pos = _start;
 State _r;
 _r = r_aname(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_3", _pos); }
 _pos = _r.pos;
 tlHandle k = _r.value;
 tlHandle _v = tlObjectFrom("k", k, null);
 return parser_pass(_p, "r_attr_3", 0, _start, state_ok(_pos, _v));
}
static State r_attr_4_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_4_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_attr_4_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr_4_1_1");*/ return _r; }
 return parser_fail(_p, "r_attr_4_1_1", _start);
}
static State r_attr_4_1_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_4_1_2", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "/");
 if (_r.ok) return parser_pass(_p, "r_attr_4_1_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr_4_1_2");*/ return _r; }
 return parser_fail(_p, "r_attr_4_1_2", _start);
}
static State r_attr_4_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attr_4_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_attr_4_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_attr_4_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_attr_4_1_2);
 if (!_r.ok) { return parser_fail(_p, "r_attr_4_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_attr_4_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_attr_4_1", 0, _start, state_ok(_pos, _v));
}
static State r_attr(Parser* _p, int _start) { // or
 parser_enter(_p, "r_attr", _start);
 int _pos = _start;
 State _r;
 _r = r_attr_1(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_attr", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr");*/ return _r; }
 _r = r_attr_2(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_attr", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr");*/ return _r; }
 _r = r_attr_3(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_attr", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr");*/ return _r; }
 _r = meta_plus(_p, _pos, r_attr_4_1, null);
 if (_r.ok) return parser_pass(_p, "r_attr", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attr");*/ return _r; }
 return parser_fail(_p, "r_attr", _start);
}
static State r_unknown_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_unknown_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "<");
 if (_r.ok) return parser_pass(_p, "r_unknown_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_unknown_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_unknown_2_1_1", _start);
}
static State r_unknown_2_1_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_unknown_2_1_2", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_unknown_2_1_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_unknown_2_1_2");*/ return _r; }
 return parser_fail(_p, "r_unknown_2_1_2", _start);
}
static State r_unknown_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_unknown_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_unknown_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_unknown_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_unknown_2_1_2);
 if (!_r.ok) { return parser_fail(_p, "r_unknown_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_unknown_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_unknown_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_unknown(Parser* _p, int _start) { // and
 parser_enter(_p, "r_unknown", _start);
 int _pos = _start;
 State _r;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_unknown", _pos); }
 _pos = _r.pos;
 _r = meta_star(_p, _pos, r_unknown_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_unknown", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlNull;
 return parser_pass(_p, "r_unknown", 0, _start, state_ok(_pos, _v));
}
static State r_escape_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_1", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\\\"");
 if (!_r.ok) { return parser_fail(_p, "r_escape_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlINT('"');
 return parser_pass(_p, "r_escape_1", 0, _start, state_ok(_pos, _v));
}
static State r_escape_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_2", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\\n");
 if (!_r.ok) { return parser_fail(_p, "r_escape_2", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlINT('\n');
 return parser_pass(_p, "r_escape_2", 0, _start, state_ok(_pos, _v));
}
static State r_escape_3(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_3", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\\r");
 if (!_r.ok) { return parser_fail(_p, "r_escape_3", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlINT('\r');
 return parser_pass(_p, "r_escape_3", 0, _start, state_ok(_pos, _v));
}
static State r_escape_4(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_4", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\\t");
 if (!_r.ok) { return parser_fail(_p, "r_escape_4", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlINT('\t');
 return parser_pass(_p, "r_escape_4", 0, _start, state_ok(_pos, _v));
}
static State r_escape_5(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_5", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\\\\");
 if (!_r.ok) { return parser_fail(_p, "r_escape_5", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlINT('\\');
 return parser_pass(_p, "r_escape_5", 0, _start, state_ok(_pos, _v));
}
static State r_escape_6_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_6_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "\"");
 if (_r.ok) return parser_pass(_p, "r_escape_6_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape_6_1");*/ return _r; }
 return parser_fail(_p, "r_escape_6_1", _start);
}
static State r_escape_6_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_6_2", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_escape_6_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape_6_2");*/ return _r; }
 return parser_fail(_p, "r_escape_6_2", _start);
}
static State r_escape_6(Parser* _p, int _start) { // and
 parser_enter(_p, "r_escape_6", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_escape_6_1);
 if (!_r.ok) { return parser_fail(_p, "r_escape_6", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_escape_6_2);
 if (!_r.ok) { return parser_fail(_p, "r_escape_6", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_escape_6", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_escape_6", 0, _start, state_ok(_pos, _v));
}
static State r_escape(Parser* _p, int _start) { // or
 parser_enter(_p, "r_escape", _start);
 int _pos = _start;
 State _r;
 _r = r_escape_1(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 _r = r_escape_2(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 _r = r_escape_3(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 _r = r_escape_4(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 _r = r_escape_5(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 _r = r_escape_6(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_escape", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_escape");*/ return _r; }
 return parser_fail(_p, "r_escape", _start);
}
static State r_aname_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "=");
 if (_r.ok) return parser_pass(_p, "r_aname_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_aname_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_aname_2_1_1", _start);
}
static State r_aname_2_1_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname_2_1_2", _start);
 int _pos = _start;
 State _r = r_sp(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_aname_2_1_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_aname_2_1_2");*/ return _r; }
 return parser_fail(_p, "r_aname_2_1_2", _start);
}
static State r_aname_2_1_3(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname_2_1_3", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_aname_2_1_3", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_aname_2_1_3");*/ return _r; }
 return parser_fail(_p, "r_aname_2_1_3", _start);
}
static State r_aname_2_1_4(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname_2_1_4", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "/>");
 if (_r.ok) return parser_pass(_p, "r_aname_2_1_4", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_aname_2_1_4");*/ return _r; }
 return parser_fail(_p, "r_aname_2_1_4", _start);
}
static State r_aname_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_aname_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_aname_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_aname_2_1_2);
 if (!_r.ok) { return parser_fail(_p, "r_aname_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_aname_2_1_3);
 if (!_r.ok) { return parser_fail(_p, "r_aname_2_1", _pos); }
 _pos = _r.pos;
 _r = meta_not(_p, _pos, r_aname_2_1_4);
 if (!_r.ok) { return parser_fail(_p, "r_aname_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_aname_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_aname_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_aname(Parser* _p, int _start) { // and
 parser_enter(_p, "r_aname", _start);
 int _pos = _start;
 State _r;
 _r = meta_plus(_p, _pos, r_aname_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_aname", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_aname", 0, _start, state_ok(_pos, _v));
}
static State r_end_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_end_2", _start);
 int _pos = _start;
 State _r = prim_any(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_end_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_end_2");*/ return _r; }
 return parser_fail(_p, "r_end_2", _start);
}
static State r_end(Parser* _p, int _start) { // and
 parser_enter(_p, "r_end", _start);
 int _pos = _start;
 State _r = meta_not(_p, _pos, r_end_2);
 if (_r.ok) return parser_pass(_p, "r_end", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_end");*/ return _r; }
 return parser_fail(_p, "r_end", _start);
}
static State r_ws_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_ws_2", _start);
 int _pos = _start;
 State _r = r_sp(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_ws_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_ws_2");*/ return _r; }
 return parser_fail(_p, "r_ws_2", _start);
}
static State r_ws(Parser* _p, int _start) { // and
 parser_enter(_p, "r_ws", _start);
 int _pos = _start;
 State _r = meta_star(_p, _pos, r_ws_2, null);
 if (_r.ok) return parser_pass(_p, "r_ws", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_ws");*/ return _r; }
 return parser_fail(_p, "r_ws", _start);
}
static State r_script_2(Parser* _p, int _start) { // or
 parser_enter(_p, "r_script_2", _start);
 int _pos = _start;
 State _r;
 _r = r_sp(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_script_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_script_2");*/ return _r; }
 _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_script_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_script_2");*/ return _r; }
 return parser_fail(_p, "r_script_2", _start);
}
static State r_script(Parser* _p, int _start) { // and
 parser_enter(_p, "r_script", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<");
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "script");
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 tlHandle name = _r.value;
 _r = meta_ahead(_p, _pos, r_script_2);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = r_attrs(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 tlHandle attrs = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 _r = r_cscript(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 tlHandle content = _r.value;
 _r = state_ok(_pos, tlSTR("open"));
 if (!_r.ok) { return parser_fail(_p, "r_script", _pos); }
 _pos = _r.pos;
 tlHandle type = _r.value;
 tlHandle _v = tlObjectFrom("name", name, "attrs", attrs, "content", content, "type", type, null);
 return parser_pass(_p, "r_script", 0, _start, state_ok(_pos, _v));
}
static State r_attrs_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attrs_2_1", _start);
 int _pos = _start;
 State _r = r_attr(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_attrs_2_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attrs_2_1");*/ return _r; }
 return parser_fail(_p, "r_attrs_2_1", _start);
}
static State r_attrs_3_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attrs_3_1", _start);
 int _pos = _start;
 State _r = r_ws(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_attrs_3_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_attrs_3_1");*/ return _r; }
 return parser_fail(_p, "r_attrs_3_1", _start);
}
static State r_attrs(Parser* _p, int _start) { // and
 parser_enter(_p, "r_attrs", _start);
 int _pos = _start;
 State _r;
 _r = meta_star(_p, _pos, r_attrs_2_1, r_attrs_3_1);
 if (!_r.ok) { return parser_fail(_p, "r_attrs", _pos); }
 _pos = _r.pos;
 tlHandle kv = _r.value;
 tlHandle _v = Object(kv);
 return parser_pass(_p, "r_attrs", 0, _start, state_ok(_pos, _v));
}
static State r_text_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_text_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "<");
 if (_r.ok) return parser_pass(_p, "r_text_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_text_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_text_2_1_1", _start);
}
static State r_text_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_text_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_text_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_text_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_text_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_text_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_text(Parser* _p, int _start) { // and
 parser_enter(_p, "r_text", _start);
 int _pos = _start;
 State _r;
 _r = meta_plus(_p, _pos, r_text_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_text", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_text", 0, _start, state_ok(_pos, _v));
}
static State r_comment_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_comment_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "--");
 if (_r.ok) return parser_pass(_p, "r_comment_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_comment_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_comment_2_1_1", _start);
}
static State r_comment_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_comment_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_comment_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_comment_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_comment_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_comment_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_comment(Parser* _p, int _start) { // and
 parser_enter(_p, "r_comment", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<");
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "!");
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "--");
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = meta_star(_p, _pos, r_comment_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "--");
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_comment", _pos); }
 _pos = _r.pos;
 tlHandle _v = tlNull;
 return parser_pass(_p, "r_comment", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_1", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_1", _pos); }
 _pos = _r.pos;
 _r = r_cdata(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_2", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_2", _pos); }
 _pos = _r.pos;
 _r = r_comment(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_2", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_2", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_3(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_3", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_3", _pos); }
 _pos = _r.pos;
 _r = r_style(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_3", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_3", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_4(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_4", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_4", _pos); }
 _pos = _r.pos;
 _r = r_script(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_4", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_4", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_5(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_5", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_5", _pos); }
 _pos = _r.pos;
 _r = r_close(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_5", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_5", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_6(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_6", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_6", _pos); }
 _pos = _r.pos;
 _r = r_open(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_6", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_6", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2_7(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq_2_7", _start);
 int _pos = _start;
 State _r;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_7", _pos); }
 _pos = _r.pos;
 _r = r_unknown(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_seq_2_7", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_seq_2_7", 0, _start, state_ok(_pos, _v));
}
static State r_seq_2(Parser* _p, int _start) { // or
 parser_enter(_p, "r_seq_2", _start);
 int _pos = _start;
 State _r;
 _r = r_seq_2_1(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_2(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_3(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_4(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_5(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_6(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_text(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 _r = r_seq_2_7(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_seq_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq_2");*/ return _r; }
 return parser_fail(_p, "r_seq_2", _start);
}
static State r_seq(Parser* _p, int _start) { // and
 parser_enter(_p, "r_seq", _start);
 int _pos = _start;
 State _r = meta_star(_p, _pos, r_seq_2, null);
 if (_r.ok) return parser_pass(_p, "r_seq", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_seq");*/ return _r; }
 return parser_fail(_p, "r_seq", _start);
}
static State r_style_2(Parser* _p, int _start) { // or
 parser_enter(_p, "r_style_2", _start);
 int _pos = _start;
 State _r;
 _r = r_sp(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_style_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_style_2");*/ return _r; }
 _r = prim_text(_p, _pos, ">");
 if (_r.ok) return parser_pass(_p, "r_style_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_style_2");*/ return _r; }
 return parser_fail(_p, "r_style_2", _start);
}
static State r_style(Parser* _p, int _start) { // and
 parser_enter(_p, "r_style", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<");
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "style");
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 tlHandle name = _r.value;
 _r = meta_ahead(_p, _pos, r_style_2);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = r_attrs(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 tlHandle attrs = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 _r = r_cstyle(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 tlHandle content = _r.value;
 _r = state_ok(_pos, tlSTR("open"));
 if (!_r.ok) { return parser_fail(_p, "r_style", _pos); }
 _pos = _r.pos;
 tlHandle type = _r.value;
 tlHandle _v = tlObjectFrom("name", name, "attrs", attrs, "content", content, "type", type, null);
 return parser_pass(_p, "r_style", 0, _start, state_ok(_pos, _v));
}
static State r_wsnl(Parser* _p, int _start) { // and
 parser_enter(_p, "r_wsnl", _start);
 int _pos = _start;
 State _r = prim_wsnl(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_wsnl", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_wsnl");*/ return _r; }
 return parser_fail(_p, "r_wsnl", _start);
}
static State r_cscript_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cscript_2_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "</script");
 if (_r.ok) return parser_pass(_p, "r_cscript_2_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_cscript_2_1_1");*/ return _r; }
 return parser_fail(_p, "r_cscript_2_1_1", _start);
}
static State r_cscript_2_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cscript_2_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_cscript_2_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_cscript_2_1", _pos); }
 _pos = _r.pos;
 _r = prim_any(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_cscript_2_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_cscript_2_1", 0, _start, state_ok(_pos, _v));
}
static State r_cscript(Parser* _p, int _start) { // and
 parser_enter(_p, "r_cscript", _start);
 int _pos = _start;
 State _r;
 _r = meta_star(_p, _pos, r_cscript_2_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_cscript", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_cscript", 0, _start, state_ok(_pos, _v));
}
static State r_close_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_close_2", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "/");
 if (_r.ok) return parser_pass(_p, "r_close_2", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_close_2");*/ return _r; }
 return parser_fail(_p, "r_close_2", _start);
}
static State r_close(Parser* _p, int _start) { // and
 parser_enter(_p, "r_close", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "<");
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, "/");
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = r_name(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 tlHandle name = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = r_attrs(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 tlHandle attrs = _r.value;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = meta_opt(_p, _pos, r_close_2);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = r_ws(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = prim_text(_p, _pos, ">");
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 _r = state_ok(_pos, tlSTR("close"));
 if (!_r.ok) { return parser_fail(_p, "r_close", _pos); }
 _pos = _r.pos;
 tlHandle type = _r.value;
 tlHandle _v = tlObjectFrom("name", name, "attrs", attrs, "type", type, null);
 return parser_pass(_p, "r_close", 0, _start, state_ok(_pos, _v));
}
static State r_string_1_1_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_1_1_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "\"");
 if (_r.ok) return parser_pass(_p, "r_string_1_1_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_string_1_1_1_1");*/ return _r; }
 return parser_fail(_p, "r_string_1_1_1_1", _start);
}
static State r_string_1_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_1_1_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_string_1_1_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_string_1_1_1", _pos); }
 _pos = _r.pos;
 _r = r_escape(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_string_1_1_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_string_1_1_1", 0, _start, state_ok(_pos, _v));
}
static State r_string_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_1", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "\"");
 if (!_r.ok) { return parser_fail(_p, "r_string_1", _pos); }
 _pos = _r.pos;
 _r = meta_star(_p, _pos, r_string_1_1_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_string_1", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 _r = prim_text(_p, _pos, "\"");
 if (!_r.ok) { return parser_fail(_p, "r_string_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_string_1", 0, _start, state_ok(_pos, _v));
}
static State r_string_2_1_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_2_1_1_1", _start);
 int _pos = _start;
 State _r = prim_text(_p, _pos, "'");
 if (_r.ok) return parser_pass(_p, "r_string_2_1_1_1", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_string_2_1_1_1");*/ return _r; }
 return parser_fail(_p, "r_string_2_1_1_1", _start);
}
static State r_string_2_1_1(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_2_1_1", _start);
 int _pos = _start;
 State _r;
 _r = meta_not(_p, _pos, r_string_2_1_1_1);
 if (!_r.ok) { return parser_fail(_p, "r_string_2_1_1", _pos); }
 _pos = _r.pos;
 _r = r_escape(_p, _pos);
 if (!_r.ok) { return parser_fail(_p, "r_string_2_1_1", _pos); }
 _pos = _r.pos;
 tlHandle _v = _r.value;
 return parser_pass(_p, "r_string_2_1_1", 0, _start, state_ok(_pos, _v));
}
static State r_string_2(Parser* _p, int _start) { // and
 parser_enter(_p, "r_string_2", _start);
 int _pos = _start;
 State _r;
 _r = prim_text(_p, _pos, "'");
 if (!_r.ok) { return parser_fail(_p, "r_string_2", _pos); }
 _pos = _r.pos;
 _r = meta_star(_p, _pos, r_string_2_1_1, null);
 if (!_r.ok) { return parser_fail(_p, "r_string_2", _pos); }
 _pos = _r.pos;
 tlHandle ts = _r.value;
 _r = prim_text(_p, _pos, "'");
 if (!_r.ok) { return parser_fail(_p, "r_string_2", _pos); }
 _pos = _r.pos;
 tlHandle _v = String(ts);
 return parser_pass(_p, "r_string_2", 0, _start, state_ok(_pos, _v));
}
static State r_string(Parser* _p, int _start) { // or
 parser_enter(_p, "r_string", _start);
 int _pos = _start;
 State _r;
 _r = r_string_1(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_string", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_string");*/ return _r; }
 _r = r_string_2(_p, _pos);
 if (_r.ok) return parser_pass(_p, "r_string", 0, _start, _r);
 if (_p->error_line) { /*print("expect: r_string");*/ return _r; }
 return parser_fail(_p, "r_string", _start);
}

#ifndef NO_VALUE
static tlHandle _xml_parse(tlTask* task, tlArgs* args) {
    tlString* code = tlStringCast(tlArgsGet(args, 0));
    if (!code) TL_THROW("expected a String");
    Parser* p = parser_new(tlStringData(code), tlStringSize(code));
    bool r = parser_parse(p, r_start);
    if (!r) {
        TL_THROW("parse error: %s at: %d:%d", p->error_msg, p->error_line, p->error_char);
    }
    return p->value;
}

void xmlparser_init() {
    tl_register_global("_xml_parse", tlNATIVE(_xml_parse, "_xml_parse"));
}
#endif


