<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>Hotel Syntax: version 1 (adapted from CoffeeScript.tmLanguage</string>
    <key>fileTypes</key>
    <array>
        <string>tl</string>
    </array>
    <key>firstLineMatch</key>
    <string>^#!.*tl</string>
    <key>name</key>
    <string>Hotel</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#nestingcomment</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^\s*###</string>
            <key>end</key>
            <string>^\s*###</string>
            <key>name</key>
            <string>comment.block.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#.*$\n?</string>
            <key>name</key>
            <string>comment.line.number-sign.hotel</string>
        </dict>

        <dict>
            <key>match</key>
            <string>(?x)
                \b(?&lt;![\.\$])(
                    break|catch|continue|return|if|while|loop
                )(?!\s*:)\b
            </string>
            <key>name</key>
            <string>keyword.control.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>(?x)
                and=|or=|!|%|&amp;|\^|\*|\/|(\-)?\-(?!&gt;)|\+\+|\+|~|==|=(?!&gt;)|!=|&lt;=|&gt;=|&lt;&lt;=|&gt;&gt;=|
                &gt;&gt;&gt;=|&lt;&gt;|&lt;|&gt;|!|&amp;&amp;|\.\.(\.)?|\?|\||\|\||\:|\*=|(?&lt;!\()/=|%=|\+=|\-=|&amp;=|
                \^=|\b(?&lt;![\.\$])(isa|and|or|xor|not)\b
            </string>
            <key>name</key>
            <string>keyword.operator.hotel</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>variable.assignment.hotel</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.separator.key-value</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.hotel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>[a-zA-Z\$_]\s*=(?!=)</string>
            <key>name</key>
            <string>variable.assignment.hotel</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(?&lt;=\s|^)([\[\{])(?=.*?[\]\}]\s+[:=])</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.hotel</string>
                </dict>
            </dict>
            <key>end</key>
            <string>([\]\}]\s*[:=])</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.hotel</string>
                </dict>
            </dict>
            <key>name</key>
            <string>meta.variable.assignment.destructured.hotel</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#variable_name</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#instance_variable</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#single_quoted_string</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#double_quoted_string</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#numeric</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.hotel</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.hotel</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.function.hotel</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.hotel</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(?x)
                (\s*)
                (?=[a-zA-Z\$_])
                (
                    [a-zA-Z\$_](\w|\$|:|\.)*\s*
                    (?=[:=](\s*\(.*\))?\s*([=-]&gt;))
                )
            </string>
            <key>name</key>
            <string>meta.function.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>-&gt;</string>
            <key>name</key>
            <string>storage.type.function.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)true(?!\s*[:=])\b</string>
            <key>name</key>
            <string>constant.language.boolean.true.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)false(?!\s*[:=])\b</string>
            <key>name</key>
            <string>constant.language.boolean.false.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)null(?!\s*[:=])\b</string>
            <key>name</key>
            <string>constant.language.null.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)undefined(?!\s*[:=])\b</string>
            <key>name</key>
            <string>constant.language.undefined.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(?&lt;!\.)(this|args|var)(?!\s*[:=])\b</string>
            <key>name</key>
            <string>variable.language.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\;</string>
            <key>name</key>
            <string>punctuation.terminator.statement.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>,[ |\t]*</string>
            <key>name</key>
            <string>meta.delimiter.object.comma.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\.</string>
            <key>name</key>
            <string>meta.delimiter.method.period.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\{|\}</string>
            <key>name</key>
            <string>meta.brace.curly.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\(|\)</string>
            <key>name</key>
            <string>meta.brace.round.hotel</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]\s*</string>
            <key>name</key>
            <string>meta.brace.square.hotel</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#double_quoted_string</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#numeric</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>nestingcomment</key>
        <dict>
            <key>begin</key>
            <string>\(#</string>
            <key>end</key>
            <string>#\)</string>
            <key>name</key>
            <string>comment.block.hotel</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#nestingcomment</string>
                </dict>
            </array>
        </dict>
        <key>double_quoted_string</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>"</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.hotel</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>"</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.hotel</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.double.hotel</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
                            <key>name</key>
                            <string>constant.character.escape.hotel</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#interpolated_hotel</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>embedded_comment</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.hotel</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(?&lt;!\\)(#).*$\n?</string>
                    <key>name</key>
                    <string>comment.line.number-sign.hotel</string>
                </dict>
            </array>
        </dict>
        <key>instance_variable</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(@)([a-zA-Z_\$]\w*)?</string>
                    <key>name</key>
                    <string>variable.other.readwrite.instance.hotel</string>
                </dict>
            </array>
        </dict>
        <key>interpolated_hotel</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>\#\{</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.embedded.hotel</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\}</string>
                    <key>name</key>
                    <string>source.hotel.embedded.source</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>$self</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>numeric</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>(?&lt;!\$)\b((0([box])[0-9a-fA-F]+)|([0-9]+(\.[0-9]+)?(e[+\-]?[0-9]+)?))\b</string>
                    <key>name</key>
                    <string>constant.numeric.hotel</string>
                </dict>
            </array>
        </dict>
        <key>single_quoted_string</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>'</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.begin.hotel</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>'</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.string.end.hotel</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>string.quoted.single.hotel</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
                            <key>name</key>
                            <string>constant.character.escape.hotel</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>variable_name</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.assignment.hotel</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>([a-zA-Z\$_]\w*(\.\w+)*)</string>
                    <key>name</key>
                    <string>variable.assignment.hotel</string>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.hotel</string>
</dict>
</plist>
